services:
  - type: web
    name: mediapipe-emotion-detection
    env: python
    plan: free
    region: oregon
    rootDir: mediapipe
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT --timeout 120 wsgi:application
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: 10000
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: GLOG_minloglevel
        value: "2"

